TOKEN = ""
ADMIN_USER_ID = 0
GROUP_NAME = ""
GROUP_FORM_URL = ""
RESPONSE_COLLECTOR_CHANNEL_ID = 0
THREAD_CHANNEL_IDS = [
    0
]
MEMBER_ROLES_MESSAGES = {
    0: "Welcome to the role"
}
MEMBER_ROLES = [
    0
]
TNGAZ_API_KEY = "foo"
GUILD_ID = 0
